plugins {
    id 'java-library'
}

dependencies {
    api project(':core-module:common-core')
    
    // Firebase FCM
    api 'com.google.firebase:firebase-admin:9.1.1'
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    
    // Redis
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    
    // Excel (Apache POI)
    implementation 'org.apache.poi:poi:5.0.0'
    implementation 'org.apache.poi:poi-ooxml:5.0.0'
    
    // Servlet API
    implementation 'jakarta.servlet:jakarta.servlet-api'
}